spring:
  application:
    name: humanChatbot
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://192.168.0.32:3306/balancelab?useUnicode=yes&characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=Asia/Seoul
    username: root
    password: 0000
  jpa:
    hibernate:
      ddl-auto: update  # 테이블 자동 생성/업데이트 (개발용, 프로덕션에서는 주의)
    show-sql: true      # SQL 쿼리 로그 출력 (디버깅용)
    properties:
      hibernate:
        format_sql: true  # SQL 포맷팅
        dialect: org.hibernate.dialect.MariaDBDialect  # MariaDB dialect 명시
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 50MB
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: your-google-client-id
            client-secret: your-google-client-secret
            scope:
              - email
              - profile
            redirect-uri: http://localhost:3000/oauth/callback
server:
  port: 8080

fastapi:
  url: http://localhost:8000

app:
  upload:
    dir: uploads  # 파일 업로드 경로