spring:
  application:
    name: balancelab
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
#    url: jdbc:mariadb://192.168.0.32:3306/balancelab?useUnicode=yes&characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=Asia/Seoul
#    username: root
#    password: 0000

    url: jdbc:mariadb://localhost:3306/balancelab?useUnicode=yes&characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=Asia/Seoul
    username: admin
    password: qwe1212!Q
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MariaDBDialect
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 50MB
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 1043262579416-q58kv975bcfbh2asisaedsmhelf1hv7s.apps.googleusercontent.com
            client-secret: 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
            scope: openid,profile,email
        provider:
          google:
            issuer-uri: https://accounts.google.com
  schedule:
    cron: 0 0 0 * * *
    use: true


server:
  port: 8080

fastapi:
  url: http://localhost:8000

app:
  upload-dir: ${user.home}/Uploads
  profiles-dir: profiles
  upload:
    dir: "Uploads"

jwt:
  secret: "jlABLRWq2cLk7h5P60OmP6S0bsX7U11WoP0+E+esOYTjEqO5T/76wHagklpzSSM/1TmEYNsDel4sMhtZfgqxpVELe2alTcpeHt6zAZ5EWNDUVbAG4/sperdfj3nFrRH3u+lNHw=="
  access-token-validity-in-milliseconds: 3600000
  refresh-token-validity-in-milliseconds: 2592000000